### PR TITLE
Fix gem to work with rails 5/bootstrap 3

### PR DESCRIPTION
**Pull request by rbclark**
The current railties version seems to lock the gem on a rather old version, this gem actually works fine with rails 5 and bootstrap 2.3 (or presumably 3 since the upstream bootstrap.file-input.js claims to support it). Since I have updated bootstrap.file-input.js to the latest version as well this presumably adds bootstrap 3 support. 

If you don't mind shipping a new version of this gem when this is merged that would be greatly appreciated.

### CODE REVIEW

**Comment by Intrepidd** [comment]
Hi ! glad to see someone is using that :) 

Can you as well update the gem version to 1.0.0 ?

**Comment by rbclark** [comment]
Yep, done!

**Comment by Intrepidd** [comment]
Thanks, just pushed v1.0.0, enjoy

**Comment by rbclark** [comment]
You're awesome, thanks!

**Pull request merged**
