### PR TITLE
Support rails 6 in gemspec

### PR DESCRIPTION
**Pull request by themilkman**
Hi there, I just bumped the railties version in the gemspec and tested it, still seems to work as expected. Would it be possible to release a new version with that?

Thanks in advance for any response!

### CODE REVIEW

**Comment by themilkman** [comment]
Hi @Intrepidd, any possibility to merge this? My repo version works fine on our Rails 6 application. Thanks!

**Comment by Intrepidd** [comment]
Hi ! Merged but this gem is highly outdated, the javascript it holds is 7 years old now :)

**Comment by themilkman** [comment]
Thanks @Intrepidd !
Yeah, I think I'll replace it soon but for now it works too good ;-)

**Comment by themilkman** [comment]
Ouh, sry for a second response, but will you also make a new release? :)

**Comment by Intrepidd** [comment]
Glad to see I helped :) 

Do you need a rubybems release?

**Comment by themilkman** [comment]
Would be great, yes :)

**Comment by Intrepidd** [comment]
Done ! https://rubygems.org/gems/bootstrap_file_input_rails/versions/1.1.0

**Comment by themilkman** [comment]
Super, thank you very much!! :-)

**Pull request merged**
